import { NextResponse } from "next/server";
import fs from "node:fs/promises";
import path from "node:path";

// Dev-only store behind the dice curation panel. POST saves a live roll as raw
// JSON under src/components/dice3d/takes/, DELETE drops one, GET lists what's
// saved (metadata only, so the dropdown stays cheap) or returns one take in full
// for replay. Every write regenerates the sibling index.ts, which is what the
// playback driver imports — so keeping a roll ships it and deleting one unships
// it, with no bake step in between. Commit the JSON + index.ts together.

const DIR = path.join(process.cwd(), "src", "components", "dice3d", "takes");
const isTakeFile = (f: string) => /^take-\d+\.json$/.test(f);

const devOnly = () =>
  process.env.NODE_ENV === "production"
    ? new NextResponse(null, { status: 404 })
    : null;

// Static imports, so the takes ride along in the client bundle. Prettier is not
// available here, so the emitted formatting has to be what prettier would print.
async function writeIndex(): Promise<number> {
  const names = (await fs.readdir(DIR)).filter(isTakeFile).sort();
  const id = (n: string) => `t${n.replace(/\D/g, "")}`;
  const body = `// GENERATED by /api/dev/keep-take — do not hand-edit.
// Every roll kept in the dev curation panel ships, and deleting one there drops
// it from this list: the kept rolls ARE the shipped set, there is no bake step.
import type { RollInTake } from "../introDriver";
${names.map((n) => `import ${id(n)} from "./${n}";`).join("\n")}

export const TAKE_NAMES = [
${names.map((n) => `  "${n}",`).join("\n")}
];

export const TAKES: RollInTake[] = [
${names.map((n) => `  ${id(n)}.take,`).join("\n")}
];
`;
  await fs.writeFile(path.join(DIR, "index.ts"), body);
  return names.length;
}

export async function POST(req: Request) {
  const blocked = devOnly();
  if (blocked) return blocked;

  const body = (await req.json()) as {
    take?: { hz: number; n: number; dice: { p: number[]; q: number[] }[] };
    meta?: unknown;
  };
  if (!body.take || body.take.dice?.length !== 4) {
    return NextResponse.json({ error: "malformed take" }, { status: 400 });
  }
  await fs.mkdir(DIR, { recursive: true });
  const name = `take-${Date.now()}.json`;
  await fs.writeFile(path.join(DIR, name), JSON.stringify(body));
  return NextResponse.json({ saved: name, count: await writeIndex() });
}

export async function DELETE(req: Request) {
  const blocked = devOnly();
  if (blocked) return blocked;

  const file = new URL(req.url).searchParams.get("file");
  // The name pattern is enforced (rather than just joined) so the param can't
  // walk out of the takes directory.
  if (!file || !isTakeFile(file)) {
    return NextResponse.json({ error: "bad file" }, { status: 400 });
  }
  try {
    await fs.unlink(path.join(DIR, file));
  } catch {
    return NextResponse.json({ error: "not found" }, { status: 404 });
  }
  return NextResponse.json({ deleted: file, count: await writeIndex() });
}

export async function GET(req: Request) {
  const blocked = devOnly();
  if (blocked) return blocked;

  const file = new URL(req.url).searchParams.get("file");

  // ?file= returns one take in full.
  if (file) {
    if (!isTakeFile(file)) {
      return NextResponse.json({ error: "bad file" }, { status: 400 });
    }
    try {
      const raw = await fs.readFile(path.join(DIR, file), "utf8");
      return new NextResponse(raw, {
        headers: { "content-type": "application/json" },
      });
    } catch {
      return NextResponse.json({ error: "not found" }, { status: 404 });
    }
  }

  // Otherwise list saved takes, newest last (filenames are save timestamps),
  // with each one's meta so the panel can judge it without fetching keyframes.
  let names: string[];
  try {
    names = (await fs.readdir(DIR)).filter(isTakeFile).sort();
  } catch {
    return NextResponse.json({ takes: [] });
  }
  const takes = await Promise.all(
    names.map(async (name) => {
      const { take, meta } = JSON.parse(
        await fs.readFile(path.join(DIR, name), "utf8"),
      );
      // Rest x per die is all the panel needs from the keyframes to flag the
      // slot-order problem; sending the streams themselves would be ~15 KB each.
      const restX = take.dice.map(
        (d: { p: number[] }) => d.p[(take.n - 1) * 3],
      );
      return { name, meta, restX, n: take.n, hz: take.hz };
    }),
  );
  return NextResponse.json({ takes });
}
