import * as THREE from "three";
import type { RollInTake } from "./introDriver";

// Orientation retcon, applied at playback (it used to happen at bake time, when
// there was a generated take set to bake it into).
//
// A die's printed faces are fixed to its local axes (Die.tsx FACES): ±Z carry
// the blue letter, ±X the orange, ±Y the pips. The body is a symmetric cube, so
// right-multiplying any cube rotation-group element s into every keyframe
// (q' = q·s) leaves the visible motion identical and only relabels which
// printed face is where. Each die draws s uniformly at random per load, so the
// scattered rest tableau keeps full orientation variety across visits — the
// same roll never reads as the same roll twice.
//
// One hard rule: the 7-pip face (only die index 1 carries one, on local −Y —
// Dice3D's tops are [2,0,2,6], bottoms 7−top) must never end pointing at the
// camera, so any s that puts its world normal at z > SEVEN_Z_MAX at the final
// keyframe is excluded from that die's draw.

// The 24 orientation-preserving symmetries of the cube, generated by BFS over
// 90° X/Y rotations from the identity. Dedup by rotated basis (q and −q are the
// same rotation, so comparing quaternions directly would double-count).
const CUBE_GROUP: THREE.Quaternion[] = (() => {
  const h = Math.SQRT1_2;
  const gens = [
    new THREE.Quaternion(h, 0, 0, h), // +90° about X
    new THREE.Quaternion(0, h, 0, h), // +90° about Y
  ];
  const key = (q: THREE.Quaternion) =>
    [
      ...new THREE.Vector3(1, 0, 0).applyQuaternion(q).toArray(),
      ...new THREE.Vector3(0, 1, 0).applyQuaternion(q).toArray(),
    ]
      .map((c) => Math.round(c))
      .join(",");
  const seen = new Map<string, THREE.Quaternion>();
  const queue = [new THREE.Quaternion()];
  seen.set(key(queue[0]), queue[0]);
  for (const q of queue) {
    for (const g of gens) {
      const next = q.clone().multiply(g);
      const k = key(next);
      if (!seen.has(k)) {
        seen.set(k, next);
        queue.push(next);
      }
    }
  }
  return [...seen.values()];
})();

// Which dice carry a 7-pip face, and its local-space normal (die index → axis).
const SEVEN_LOCAL: Record<number, THREE.Vector3> = {
  1: new THREE.Vector3(0, -1, 0),
};
// A symmetry is excluded if it leaves the 7 face's world normal more camera-ward
// than this at rest. The group maps the face to (near-)axis directions, so
// values cluster around {0, ±0.9+}; 0.25 cleanly splits them.
const SEVEN_Z_MAX = 0.25;

/**
 * One symmetry per die for this playback. `pinned` picks deterministically, so
 * a panel replay (or ?sim=N) re-watches an identical roll down to the faces.
 */
export function drawRetcon(
  take: RollInTake,
  pinned: boolean,
): THREE.Quaternion[] {
  const last = take.n - 1;
  return take.dice.map((die, i) => {
    const qFinal = new THREE.Quaternion().fromArray(die.q, last * 4);
    const seven = SEVEN_LOCAL[i];
    // At most 3 of the 6 face directions can land at z > 0.25, so at most 12 of
    // the 24 are excluded — the pool is never empty.
    const pool = seven
      ? CUBE_GROUP.filter(
          (s) =>
            seven.clone().applyQuaternion(qFinal.clone().multiply(s)).z <=
            SEVEN_Z_MAX,
        )
      : CUBE_GROUP;
    return pool[pinned ? 0 : Math.floor(Math.random() * pool.length)];
  });
}
