// Builds the interactive ER diagram (Liam ERD) from the migration SQL into
// public/schema-erd, where /admin/schema/erd iframes it. Same approach as
// arbiter's /schema page. Output is gitignored; next.config.ts calls this on
// every production build and on dev start, so nothing is regenerated by hand.
import { execFileSync } from "node:child_process";
import { existsSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";

const MIGRATIONS = "drizzle";
const OUT = join("public", "schema-erd");

function newestMigrationMtime() {
  return Math.max(
    0,
    ...readdirSync(MIGRATIONS)
      .filter((f) => f.endsWith(".sql"))
      .map((f) => statSync(join(MIGRATIONS, f)).mtimeMs),
  );
}

/** Rebuilds unless the output is already newer than every migration file. */
export function buildErd({ force = false } = {}) {
  const index = join(OUT, "index.html");
  if (
    !force &&
    existsSync(index) &&
    statSync(index).mtimeMs > newestMigrationMtime()
  ) {
    return;
  }
  execFileSync(
    "pnpm",
    [
      "exec",
      "liam",
      "erd",
      "build",
      "--input",
      `${MIGRATIONS}/*.sql`,
      "--format",
      "postgres",
      "--output-dir",
      OUT,
    ],
    { stdio: "inherit" },
  );
}

if (process.argv[1] && import.meta.url.endsWith(process.argv[1])) {
  buildErd({ force: true });
}
