// Recording harness for the dice roll-in: runs the live Rapier sim in a headless
// browser (?record=1) a bunch of times, scores the finished takes, keeps the
// best, and bakes them into src/components/dice3d/rollInTakes.ts for the
// playback driver to ship. Rerun after tuning physicsRollIn.ts.
//
//   node scripts/record-rollin.mjs [--runs 14] [--keep 5] [--jobs 4] [--port 4600] [--url http://...]
//
// Pass --url to use an already-running dev server; otherwise the script starts
// `next dev` on --port and kills it when done.

import { spawn } from "node:child_process";
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { chromium } from "playwright";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "src/components/dice3d/rollInTakes.ts");

const arg = (name, dflt) => {
  const i = process.argv.indexOf(`--${name}`);
  return i > -1 ? process.argv[i + 1] : dflt;
};
const RUNS = Number(arg("runs", 14));
const KEEP = Number(arg("keep", 5));
const PORT = Number(arg("port", 4600));
// Concurrent pages. Safe because each run is an independent page load and the
// sim advances by fixed steps of accumulated (dt-clamped) frame time — slow,
// contended rendering only stretches a run's wall clock, never its outcome.
const JOBS = Number(arg("jobs", 4));
let url = arg("url", null);

// --- bake-time META-out retcon --------------------------------------------
// A die's printed faces are fixed to its local axes (Die.tsx FACES): ±Z carry
// the blue letter, ±X the orange, ±Y the pips — opposite faces are duplicates.
// The body is a symmetric cube, so right-multiplying any cube rotation-group
// element s into EVERY keyframe (q' = q·s) leaves the visible motion identical
// and only relabels which printed face is where. We exploit that per die: pick
// the s that best turns a blue face toward the camera (world +Z) at the take's
// FINAL keyframe, so each die comes to rest already showing META-ish and the
// align tail is a small square-up instead of an arbitrary reveal twist.
//
// Quaternions are [x, y, z, w] flat arrays throughout.

const qMul = (a, b) => [
  a[3] * b[0] + a[0] * b[3] + a[1] * b[2] - a[2] * b[1],
  a[3] * b[1] - a[0] * b[2] + a[1] * b[3] + a[2] * b[0],
  a[3] * b[2] + a[0] * b[1] - a[1] * b[0] + a[2] * b[3],
  a[3] * b[3] - a[0] * b[0] - a[1] * b[1] - a[2] * b[2],
];
// Rotate a vector by a quaternion (v' = q·v·q⁻¹, expanded).
const qRotate = (q, v) => {
  const [x, y, z, w] = q;
  const tx = 2 * (y * v[2] - z * v[1]);
  const ty = 2 * (z * v[0] - x * v[2]);
  const tz = 2 * (x * v[1] - y * v[0]);
  return [
    v[0] + w * tx + y * tz - z * ty,
    v[1] + w * ty + z * tx - x * tz,
    v[2] + w * tz + x * ty - y * tx,
  ];
};

// The 24 orientation-preserving symmetries of the cube, generated by BFS over
// 90° X/Y rotations from the identity. Dedup by rotated basis (q and -q are
// the same rotation, so comparing quaternions directly would double-count).
const CUBE_GROUP = (() => {
  const h = Math.SQRT1_2;
  const gens = [
    [h, 0, 0, h], // +90° about X
    [0, h, 0, h], // +90° about Y
  ];
  const seen = new Map();
  const key = (q) =>
    [...qRotate(q, [1, 0, 0]), ...qRotate(q, [0, 1, 0])]
      .map((c) => Math.round(c))
      .join(",");
  const queue = [[0, 0, 0, 1]];
  seen.set(key(queue[0]), queue[0]);
  for (const q of queue) {
    for (const g of gens) {
      const next = qMul(q, g);
      const k = key(next);
      if (!seen.has(k)) {
        seen.set(k, next);
        queue.push(next);
      }
    }
  }
  return [...seen.values()];
})();
if (CUBE_GROUP.length !== 24)
  throw new Error(`cube group has ${CUBE_GROUP.length} elements, expected 24`);

// Retcon one take in place. Per die: score each s by how camera-ward a blue
// face ends up at the final keyframe — |world-Z of the retconned local Z axis|
// (abs because ±Z are both blue) — tie-broken by pips toward world +Y the same
// way. Opposite-face duplication makes several of the 24 tie exactly; any
// argmax is fine. Returns the per-die blue-face·camera dot for logging.
function retconTake(take) {
  return take.dice.map((die) => {
    const qFinal = die.q.slice((take.n - 1) * 4, take.n * 4);
    let best = null;
    let bestBlue = -Infinity;
    let bestPip = -Infinity;
    for (const s of CUBE_GROUP) {
      const q = qMul(qFinal, s);
      const blue = Math.abs(qRotate(q, [0, 0, 1])[2]);
      const pip = Math.abs(qRotate(q, [0, 1, 0])[1]);
      if (blue > bestBlue + 1e-9 || (blue > bestBlue - 1e-9 && pip > bestPip)) {
        best = s;
        bestBlue = blue;
        bestPip = pip;
      }
    }
    for (let k = 0; k < take.n; k++) {
      const q = qMul(die.q.slice(k * 4, k * 4 + 4), best);
      for (let c = 0; c < 4; c++) die.q[k * 4 + c] = Number(q[c].toFixed(4));
    }
    return bestBlue;
  });
}

// A take is usable only if the sim settled on its own with every die resting
// near its slot, nothing ever strayed toward the z walls, and the rest
// positions stay in slot order with a safe gap — the align slide is a
// straight kinematic lerp to the slots, so an order inversion (or a too-tight
// pair) would sweep one die through another, the very artifact this replaces.
// Kicked/tilted rest poses are deliberately kept: the retcon's dot-product
// scoring works fine on a tilted die, and the align tail settles it the rest
// of the way. (Fully stacked dice can't slip through — a stack triggers the
// sim's nudge/timeout path, which the nudges/timedOut checks reject.)
function usable(take, meta) {
  const restX = take.dice.map((d) => d.p[(take.n - 1) * 3]);
  const ordered = restX.every((x, i) => i === 0 || x - restX[i - 1] >= 1.0);
  return (
    ordered &&
    !meta.timedOut &&
    meta.nudges === 0 &&
    meta.duration <= 3.0 &&
    meta.finalErr.every((e) => e <= 0.9) &&
    meta.maxAbsZ <= 1.2
  );
}
// Among usable takes prefer tight landings, then quick settles.
const score = (meta) =>
  meta.finalErr.reduce((a, b) => a + b, 0) + 0.3 * meta.duration;

let server = null;
if (!url) {
  console.log(`starting next dev on :${PORT}...`);
  server = spawn("pnpm", ["exec", "next", "dev", "--port", String(PORT)], {
    cwd: ROOT,
    stdio: "ignore",
    detached: true,
  });
  url = `http://localhost:${PORT}`;
  // Poll until the server answers.
  for (let i = 0; ; i++) {
    try {
      await fetch(url);
      break;
    } catch {
      if (i > 120) throw new Error("dev server never came up");
      await new Promise((r) => setTimeout(r, 500));
    }
  }
}

const browser = await chromium.launch({
  args: ["--use-gl=swiftshader", "--enable-unsafe-swiftshader"],
});

const takes = [];
let nextRun = 0;
async function worker() {
  for (let run = nextRun++; run < RUNS; run = nextRun++) {
    const page = await browser.newPage({
      viewport: { width: 1280, height: 800 },
    });
    try {
      await page.goto(`${url}/?record=1`, { waitUntil: "domcontentloaded" });
      // Generous timeout: JOBS-way contended swiftshader frames are slow, and
      // the dt clamp makes slow frames stretch a run's wall clock.
      await page.waitForFunction(
        () => window.__rollInTake !== undefined,
        null,
        {
          timeout: 90000,
        },
      );
      const { take, meta } = await page.evaluate(() => window.__rollInTake);
      const ok = usable(take, meta);
      // Retcon usable takes so a blue face ends camera-ward (see above); the
      // returned dots say how square-on each die's letter rests before the tail.
      const blueDots = ok ? retconTake(take) : null;
      console.log(
        `run ${run + 1}/${RUNS}: ${ok ? "keep?" : "reject"} ` +
          `dur=${meta.duration.toFixed(2)}s err=[${meta.finalErr.map((e) => e.toFixed(2)).join(",")}] ` +
          `y=[${meta.finalY.map((y) => y.toFixed(2)).join(",")}] nudges=${meta.nudges}${meta.timedOut ? " TIMEOUT" : ""}` +
          (blueDots
            ? ` blue=[${blueDots.map((b) => b.toFixed(2)).join(",")}]`
            : ""),
      );
      if (ok) takes.push({ take, meta, score: score(meta) });
    } catch (e) {
      console.log(
        `run ${run + 1}/${RUNS}: failed (${e.message.split("\n")[0]})`,
      );
    } finally {
      await page.close();
    }
  }
}
try {
  await Promise.all(Array.from({ length: JOBS }, worker));
} finally {
  await browser.close();
  if (server) process.kill(-server.pid, "SIGTERM");
}

if (takes.length < KEEP) {
  console.error(
    `only ${takes.length} usable takes (< ${KEEP}); not writing. ` +
      `Loosen criteria or add --runs.`,
  );
  process.exit(1);
}

takes.sort((a, b) => a.score - b.score);
const kept = takes.slice(0, KEEP);
const body = kept.map((t) => JSON.stringify(t.take)).join(",\n  ");
writeFileSync(
  OUT,
  `import type { RollInTake } from "./introDriver";

// Baked roll-in takes — GENERATED, do not hand-edit.
// Regenerate after tuning physicsRollIn.ts with: node scripts/record-rollin.mjs
// (runs the live sim under ?record=1 a bunch of times, keeps the takes that
// settle cleanly nearest their slots, and rewrites this file). Each die's
// quaternion stream has a cube-symmetry retcon baked in so a blue META face
// rests roughly camera-ward at the final keyframe; pin one with ?sim=N to review.
export const TAKES: RollInTake[] = [
  ${body},
];
`,
);
console.log(
  `wrote ${KEEP} takes to ${OUT} ` +
    `(settle times: ${kept.map((t) => t.meta.duration.toFixed(2) + "s").join(", ")})`,
);
