// Recording harness for the dice roll-in: runs the live Rapier sim in a headless
// browser (?record=1) a bunch of times, scores the finished takes, keeps the
// best, and bakes them into src/components/dice3d/rollInTakes.ts for the
// playback driver to ship. Rerun after tuning physicsRollIn.ts.
//
//   node scripts/record-rollin.mjs [--runs 14] [--keep 5] [--jobs 4] [--port 4600] [--url http://...] [--launch low]
//
// Pass --url to use an already-running dev server; otherwise the script starts
// `next dev` on --port and kills it when done.

import { spawn } from "node:child_process";
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { chromium } from "playwright";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "src/components/dice3d/rollInTakes.ts");

const arg = (name, dflt) => {
  const i = process.argv.indexOf(`--${name}`);
  return i > -1 ? process.argv[i + 1] : dflt;
};
const RUNS = Number(arg("runs", 14));
const KEEP = Number(arg("keep", 5));
const PORT = Number(arg("port", 4600));
// Concurrent pages. Safe because each run is an independent page load and the
// sim advances by fixed steps of accumulated (dt-clamped) frame time — slow,
// contended rendering only stretches a run's wall clock, never its outcome.
const JOBS = Number(arg("jobs", 4));
// Launch profile for the live sim (physicsRollIn.ts PROFILES): the default
// high lob, or the low ground-skim style via --launch low.
const LAUNCH = arg("launch", "high");
let url = arg("url", null);

// --- bake-time orientation retcon -------------------------------------------
// A die's printed faces are fixed to its local axes (Die.tsx FACES): ±Z carry
// the blue letter, ±X the orange, ±Y the pips. The body is a symmetric cube,
// so right-multiplying any cube rotation-group element s into EVERY keyframe
// (q' = q·s) leaves the visible motion identical and only relabels which
// printed face is where. Earlier bakes used that to force a blue face
// camera-ward at rest; the align tail's slerp to the META pose does that
// reveal on its own, so the retcon is now looser: each die draws s UNIFORMLY
// at random so the scattered rest tableau keeps full orientation variety.
// One hard rule survives: the 7-pip face (only die index 1 carries one, on
// local −Y — Dice3D's tops are [2,0,2,6], bottoms 7−top) must never end
// pointing at the camera, so any s that puts its world normal at
// z > SEVEN_Z_MAX at the final keyframe is excluded from that die's draw.
//
// Quaternions are [x, y, z, w] flat arrays throughout.

const qMul = (a, b) => [
  a[3] * b[0] + a[0] * b[3] + a[1] * b[2] - a[2] * b[1],
  a[3] * b[1] - a[0] * b[2] + a[1] * b[3] + a[2] * b[0],
  a[3] * b[2] + a[0] * b[1] - a[1] * b[0] + a[2] * b[3],
  a[3] * b[3] - a[0] * b[0] - a[1] * b[1] - a[2] * b[2],
];
// Rotate a vector by a quaternion (v' = q·v·q⁻¹, expanded).
const qRotate = (q, v) => {
  const [x, y, z, w] = q;
  const tx = 2 * (y * v[2] - z * v[1]);
  const ty = 2 * (z * v[0] - x * v[2]);
  const tz = 2 * (x * v[1] - y * v[0]);
  return [
    v[0] + w * tx + y * tz - z * ty,
    v[1] + w * ty + z * tx - x * tz,
    v[2] + w * tz + x * ty - y * tx,
  ];
};

// The 24 orientation-preserving symmetries of the cube, generated by BFS over
// 90° X/Y rotations from the identity. Dedup by rotated basis (q and -q are
// the same rotation, so comparing quaternions directly would double-count).
const CUBE_GROUP = (() => {
  const h = Math.SQRT1_2;
  const gens = [
    [h, 0, 0, h], // +90° about X
    [0, h, 0, h], // +90° about Y
  ];
  const seen = new Map();
  const key = (q) =>
    [...qRotate(q, [1, 0, 0]), ...qRotate(q, [0, 1, 0])]
      .map((c) => Math.round(c))
      .join(",");
  const queue = [[0, 0, 0, 1]];
  seen.set(key(queue[0]), queue[0]);
  for (const q of queue) {
    for (const g of gens) {
      const next = qMul(q, g);
      const k = key(next);
      if (!seen.has(k)) {
        seen.set(k, next);
        queue.push(next);
      }
    }
  }
  return [...seen.values()];
})();
if (CUBE_GROUP.length !== 24)
  throw new Error(`cube group has ${CUBE_GROUP.length} elements, expected 24`);

// Which dice carry a 7-pip face, and its local-space normal (die index → axis).
const SEVEN_LOCAL = { 1: [0, -1, 0] };
// A symmetry is excluded if it leaves the 7 face's world normal more
// camera-ward than this at rest. The group maps the face to (near-)axis
// directions, so values cluster around {0, ±0.9+}; 0.25 cleanly splits them.
const SEVEN_Z_MAX = 0.25;

// Retcon one take in place. Per die: draw s uniformly from the cube group —
// minus, for a 7-carrying die, the symmetries that would point the 7 at the
// camera (at most 3 of the 6 face directions can have z > 0.25, so at most 12
// of 24 are excluded; the pool is never empty). Returns the per-die 7-face
// world z at rest (null for dice with no 7) for logging.
function retconTake(take) {
  return take.dice.map((die, i) => {
    const qFinal = die.q.slice((take.n - 1) * 4, take.n * 4);
    const seven = SEVEN_LOCAL[i];
    const pool = seven
      ? CUBE_GROUP.filter(
          (s) => qRotate(qMul(qFinal, s), seven)[2] <= SEVEN_Z_MAX,
        )
      : CUBE_GROUP;
    const s = pool[Math.floor(Math.random() * pool.length)];
    for (let k = 0; k < take.n; k++) {
      const q = qMul(die.q.slice(k * 4, k * 4 + 4), s);
      for (let c = 0; c < 4; c++) die.q[k * 4 + c] = Number(q[c].toFixed(4));
    }
    return seven ? qRotate(qMul(qFinal, s), seven)[2] : null;
  });
}

// --- on-screen keep criterion -----------------------------------------------
// The visible canvas edge is ~±3.2 in local units (introDriver.ts BOUNDS
// comment); require a 0.1 margin at ±EDGE. A die's true x-reach at a keyframe:
// the beveled body is the Minkowski sum of a 0.44-half-width cube and an
// r=0.06 sphere (matching both the visual RoundedBox and the sim collider),
// so its support along x is 0.44·Σ|basis.x| + 0.06 over the rotated local
// basis — exact, from 0.5 face-on up to ~0.822 corner-on. The sim walls
// hard-bound colliders at ±3.10 inner faces (± transient impact penetration);
// this rejects the takes that press against them. (Extent is invariant under
// the retcon — a cube symmetry only permutes/signs the basis — so checking
// pre-retcon quaternions is exact.)
const EDGE = 3.1;
const halfExtentX = (q) =>
  0.44 *
    (Math.abs(qRotate(q, [1, 0, 0])[0]) +
      Math.abs(qRotate(q, [0, 1, 0])[0]) +
      Math.abs(qRotate(q, [0, 0, 1])[0])) +
  0.06;

// Every die must stay fully on camera from the moment it matters: clear of the
// RIGHT edge from first floor contact on (the flight approaches from the left,
// so the right edge is only reachable once landed/bouncing), and clear of the
// LEFT edge from the moment the die has fully entered the frame — the
// off-screen-left entry itself is by design. The final keyframe falls in both
// windows, so the rest tableau sits inside ±EDGE. Returns the worst reach
// toward each edge alongside the verdict so runs can log how close they came.
function screenStats(take) {
  let ok = true;
  let maxRight = -Infinity; // worst landed x-reach toward the right edge
  let minLeft = Infinity; // worst post-entry x-reach toward the left edge
  for (const die of take.dice) {
    let touched = false; // has reached the floor (TOUCH_Y in physicsRollIn.ts)
    let entered = false; // has been fully inside the left edge
    for (let k = 0; k < take.n; k++) {
      const x = die.p[k * 3];
      const h = halfExtentX(die.q.slice(k * 4, k * 4 + 4));
      if (die.p[k * 3 + 1] < 0.55) touched = true;
      if (touched) maxRight = Math.max(maxRight, x + h);
      if (x - h >= -EDGE) entered = true;
      if (entered) minLeft = Math.min(minLeft, x - h);
    }
    if (!touched || !entered) ok = false;
  }
  return { ok: ok && maxRight <= EDGE && minLeft >= -EDGE, maxRight, minLeft };
}

// A take is usable only if the sim settled on its own with every die resting
// near its slot, nothing ever strayed toward the z walls, every die stays
// fully on camera per screenStats above, and the rest positions stay in slot
// order with a safe gap — the align slide is a straight kinematic lerp to the
// slots, so an order inversion (or a too-tight pair) would sweep one die
// through another, the very artifact this replaces. Kicked/tilted rest poses
// are deliberately kept — the align tail settles them the rest of the way.
// (Fully stacked dice can't slip through — a stack triggers the sim's
// nudge/timeout path, which the nudges/timedOut checks reject.)
function usable(take, meta, screen) {
  const restX = take.dice.map((d) => d.p[(take.n - 1) * 3]);
  const ordered = restX.every((x, i) => i === 0 || x - restX[i - 1] >= 1.0);
  return (
    ordered &&
    !meta.crashed &&
    !meta.timedOut &&
    meta.nudges === 0 &&
    meta.duration <= 3.0 &&
    meta.finalErr.every((e) => e <= 0.9) &&
    meta.maxAbsZ <= 1.2 &&
    screen.ok
  );
}
// Among usable takes prefer tight landings, then quick settles.
const score = (meta) =>
  meta.finalErr.reduce((a, b) => a + b, 0) + 0.3 * meta.duration;

let server = null;
if (!url) {
  console.log(`starting next dev on :${PORT}...`);
  server = spawn("pnpm", ["exec", "next", "dev", "--port", String(PORT)], {
    cwd: ROOT,
    stdio: "ignore",
    detached: true,
  });
  url = `http://localhost:${PORT}`;
  // Poll until the server answers.
  for (let i = 0; ; i++) {
    try {
      await fetch(url);
      break;
    } catch {
      if (i > 120) throw new Error("dev server never came up");
      await new Promise((r) => setTimeout(r, 500));
    }
  }
}

const browser = await chromium.launch({
  args: ["--use-gl=swiftshader", "--enable-unsafe-swiftshader"],
});

const takes = [];
let nextRun = 0;
async function worker() {
  for (let run = nextRun++; run < RUNS; run = nextRun++) {
    const page = await browser.newPage({
      viewport: { width: 1280, height: 800 },
    });
    try {
      await page.goto(
        `${url}/?record=1${LAUNCH === "high" ? "" : `&launch=${LAUNCH}`}`,
        { waitUntil: "domcontentloaded" },
      );
      // Generous timeout: JOBS-way contended swiftshader frames are slow, and
      // the dt clamp makes slow frames stretch a run's wall clock.
      await page.waitForFunction(
        () => window.__rollInTake !== undefined,
        null,
        {
          timeout: 90000,
        },
      );
      const { take, meta } = await page.evaluate(() => window.__rollInTake);
      const screen = screenStats(take);
      const ok = usable(take, meta, screen);
      // Retcon usable takes (uniform-random symmetry, 7-face rule — see
      // above); the returned values log where die 1's 7 face ended up.
      const sevenZ = ok ? retconTake(take) : null;
      console.log(
        `run ${run + 1}/${RUNS}: ${ok ? "keep?" : "reject"} ` +
          `dur=${meta.duration.toFixed(2)}s err=[${meta.finalErr.map((e) => e.toFixed(2)).join(",")}] ` +
          `y=[${meta.finalY.map((y) => y.toFixed(2)).join(",")}] ` +
          `ext=[${screen.minLeft.toFixed(2)},${screen.maxRight.toFixed(2)}] ` +
          `nudges=${meta.nudges}${meta.timedOut ? " TIMEOUT" : ""}${meta.crashed ? " CRASH" : ""}` +
          (sevenZ
            ? ` sevenZ=[${sevenZ.map((v) => (v === null ? "-" : v.toFixed(2))).join(",")}]`
            : ""),
      );
      if (ok) takes.push({ take, meta, score: score(meta) });
    } catch (e) {
      console.log(
        `run ${run + 1}/${RUNS}: failed (${e.message.split("\n")[0]})`,
      );
    } finally {
      await page.close();
    }
  }
}
try {
  await Promise.all(Array.from({ length: JOBS }, worker));
} finally {
  await browser.close();
  if (server) process.kill(-server.pid, "SIGTERM");
}

if (takes.length < KEEP) {
  console.error(
    `only ${takes.length} usable takes (< ${KEEP}); not writing. ` +
      `Loosen criteria or add --runs.`,
  );
  process.exit(1);
}

takes.sort((a, b) => a.score - b.score);
const kept = takes.slice(0, KEEP);
const body = kept.map((t) => JSON.stringify(t.take)).join(",\n  ");
writeFileSync(
  OUT,
  `import type { RollInTake } from "./introDriver";

// Baked roll-in takes — GENERATED, do not hand-edit.
// Regenerate after tuning physicsRollIn.ts with: node scripts/record-rollin.mjs
// (runs the live sim under ?record=1 a bunch of times, keeps the takes that
// settle cleanly nearest their slots and fully on camera, and rewrites this
// file). Each die's quaternion stream has a uniform-random cube-symmetry
// retcon baked in — visually inert, keeps the rest tableau varied — with die
// index 1's 7-pip face guaranteed to never face the camera at rest; pin a
// take with ?sim=N to review.
export const TAKES: RollInTake[] = [
  ${body},
];
`,
);
console.log(
  `wrote ${KEEP} takes to ${OUT} ` +
    `(settle times: ${kept.map((t) => t.meta.duration.toFixed(2) + "s").join(", ")})`,
);
